compile pass tc001.curry
compile fail tc002.curry
compile fail tc003.curry
compile pass tc004.curry
compile pass tc005.curry
compile pass tc006.curry
compile pass tc007.curry
compile fail tc008.curry
compile pass tc009.curry
run pass tc010.curry
compile fail tc011.curry
compile fail tc012.curry
compile fail tc013.curry
compile fail tc014.curry
compile fail tc015.curry
compile pass tc016.curry
compile fail tc017.curry
compile fail tc018.curry
compile fail tc019.curry
compile pass tc020.curry
compile fail tc021.curry
compile fail tc022.curry
compile fail tc023.curry
compile fail tc024.curry
compile fail tc025.curry
run pass tc026.curry
compile fail tc027.curry
compile pass tc028.curry
compile fail tc029.curry
run pass tc030.curry
compile pass tc031.curry
run pass tc032.curry
run pass tc033.curry
run pass tc034.curry
run pass tc035.curry
compile fail tc036.curry
run pass tc037.curry
compile pass tc038.curry
compile pass tc039.curry
compile pass tc040.curry
type pass tc040.curry f1''
type pass tc040.curry f2''
type pass tc041.curry zero
type pass tc041.curry add
type pass tc042.curry left
type pass tc042.curry common
type pass tc042.curry right
type pass tc042.curry l
type pass tc042.curry c
type pass tc042.curry r
type pass tc042.curry new
type pass tc042.curry n
type pass tc043.curry incr
type pass tc043.curry tautology
